import json
import requests

import auth

token = auth.get_token()

# Setup Config
with open("config.json") as f:
    config = json.load(f) 

exclude_other_users = config["exclude"]["exclude_other_users"]
exclude_playlists = config["exclude"]["playlists"]
exclude_songs = config["exclude"]["songs"]

headers = {
    "User-Agent": "Python",
    "Authorization": f"Bearer {token}"
}

me_uri = json.loads(requests.request("GET", "https://api.spotify.com/v1/me", headers=headers).text)["uri"]

print(me_uri)


# Creating Playlist
playlists_url = "https://api.spotify.com/v1/me/playlists/"

payload = {
    "name": "EVERYTHING",
    "description": "Playlist with everything. Generated by https://github.com/Parkman145/Everything-Playlist"
}
headers = {
    "Content-Type": "application/json",
    "User-Agent": "python",
    "Authorization": f"Bearer {token}"
}

playlist_create_response_body = json.loads(requests.request("POST", playlists_url, json=payload, headers=headers).content)

EVERYTHING_playlist_id = playlist_create_response_body["id"]

