import json
import requests
from time import sleep
import auth
import requests_cache
import math

def create_playlist(name: str) -> str:
    playlists_url = "https://api.spotify.com/v1/me/playlists/"

    payload = {
    "name": "EVERYTHING",
    "description": "Playlist with everything. Generated by https://github.com/Parkman145/Everything-Playlist"
    }

    headers = {
    "Content-Type": "application/json",
    "User-Agent": "python",
    "Authorization": f"Bearer {token}"
    }

    response = requests.request("POST", playlists_url, json=payload, headers=headers)
    body = json.loads(response.content)


    id = body["id"]

    return id

# Holy name
def get_song_ids_and_album_urls_from_playlist(playlist_id):
    global error_song_count

    playlist_url = f"https://api.spotify.com/v1/playlists/{playlist_id}/items"
    headers = {
    "Content-Type": "application/json",
    "User-Agent": "python",
    "Authorization": f"Bearer {token}"
    }
    
    playlist_response = json.loads(requests.request("GET", playlist_url, headers=headers).content)
    
    song_ids = set()
    large_album_images = set()
    medium_album_images = set()
    small_album_images = set()
    
    for song in playlist_response["items"]:
        song_id = song.get("item").get("id")
        if (not song_id):
            error_song_count += 1
            continue

        large_album_image, medium_album_image, small_album_image = song.get("item").get("album").get("images")

        song_ids.add(song_id)
        large_album_images.add(large_album_image.get("url"))
        medium_album_images.add(medium_album_image.get("url"))
        small_album_images.add(small_album_image.get("url"))
    return (song_ids, large_album_images, medium_album_images, small_album_images)


token = auth.get_token()


requests_cache.install_cache('demo_cache', expire_after=3600, ignored_parameters=[])


# Setup Config
with open("config.json") as f:
    config = json.load(f) 

exclude_other_users = config["exclude"]["exclude_other_users"]
exclude_playlists = config["exclude"]["playlists"]
exclude_songs = config["exclude"]["songs"]

headers = {
    "User-Agent": "Python",
    "Authorization": f"Bearer {token}"
}

me_uri = json.loads(requests.request("GET", "https://api.spotify.com/v1/me", headers=headers).text)["uri"]

print(me_uri)


# Creating Playlist

headers = {
    "Content-Type": "application/json",
    "User-Agent": "python",
    "Authorization": f"Bearer {token}"
}


EVERYTHING_playlist_id = create_playlist("EVERYTHING")

print(EVERYTHING_playlist_id)

seen_albums = set()
seen_songs = set()
song_uris = []

current_playlists_url = playlists_url

playlists_counter = 0
error_song_count = 0

while True:
    response = requests.request("GET", current_playlists_url, headers=headers)
    playlists = json.loads(response.text)
    total_songs = playlists["total"]

    for playlist in playlists["items"]:
        if playlist["id"] in exclude_playlists or playlist["name"] in exclude_playlists:
            continue
        playlist_url = playlist["href"]
        playlist_response = json.loads(requests.request("GET", playlist_url, headers=headers).content)
        if exclude_other_users and (playlist_response["owner"]["uri"] != me_uri):
            continue
        
        for song in playlist_response["items"]["items"]:
            try:
                song_id = song["item"]["id"]
                album_id = song["item"]["album"]["id"]
            except TypeError:
                error_song_count += 1
                continue

            if song_id not in seen_songs:
                seen_songs.add(song_id)
                song_uris.append(f"spotify:track:{song_id}")
        playlists_counter += 1
        print(f"\rPlaylists Checked: {playlists_counter}/{total_songs}, Error with {error_song_count} songs                     ", end="")

    if playlists["next"]:
        current_playlists_url = playlists["next"]
    else: break

while song_uris:
    url = f"https://api.spotify.com/v1/playlists/{EVERYTHING_playlist_id}/items"

    payload = {"uris": song_uris[:100]}
    headers = {
        "Content-Type": "application/json",
        "User-Agent": "Python",
        "Authorization": f"Bearer {token}"
    }

    response = requests.request("POST", url, json=payload, headers=headers)

    if response.status_code == 429:
        sleep(1)
        continue

    song_uris = song_uris[100:]
